apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
  namespace: tekton-pipelines-run
spec:
  workspaces:
    - name: git-source
      description: The git repo
  params:
    - name: gitUrl
      description: Git repository url
    - name: gitRevision
      description: Git revision
      default: master
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
    - name: imageUrl
      description: Image name including repository
    - name: imageTag
      description: Image tag
      default: "latest"
    - name: imageName
      description: Name of the image
    - name: gitDestination
      description: gitDestination
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(params.gitRevision)"
        - name: subdirectory
          value: "source"
        - name: deleteExisting
          value: "true"

    - name: clone-repo-destination-beta
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.gitDestination)"
        - name: revision
          value: "cluster0-staging"
        - name: subdirectory
          value: "destination-cluster0-staging"
        - name: deleteExisting
          value: "true"

    - name: source-to-image
      taskRef:
        name: kaniko
      runAfter:
        - clone-repo
      workspaces:
        - name: source
          workspace: git-source
      params:
        - name: CONTEXT
          value: source/$(params.pathToContext)
        - name: IMAGE
          value: $(params.imageUrl):$(params.imageTag)



    - name: deploy-to-beta-git
      taskRef:
        name: deploy-to-git
      runAfter:
        - source-to-image
        - clone-repo-destination-beta
      workspaces:
        - name: git-source
          workspace: git-source
      params:
        - name: imageUrl
          value: $(params.imageUrl)
        - name: imageTag
          value: $(params.imageTag)
        - name: imageName
          value: $(params.imageName)
        - name: gitDestination
          value: $(params.gitDestination)
        - name: branch
          value: "cluster0-staging"
