apiVersion: v1
kind: Secret
metadata:
  name: harbor-account
  namespace: tekton-pipelines-run
  annotations:
    tekton.dev/docker-0: https://harbor.c0.kube8.ga
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <pwd>

---

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-account
  namespace: tekton-pipelines-run
  annotations:
    tekton.dev/git-0: https://gitlab.c0.kube8.ga
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <pwd>
